"""Cost-per-resolution and ROI of automating dispute intake, from the dataset plus the held-out evaluation.

Run: uv run python -m src.eda.roi   (needs the raw mirror: make download)
Writes reports/roi_analysis.md. Every figure is either queried here or read from the evaluation results; the only
inputs that are not data are the ASSUMPTIONS below, which the report states and varies."""
import json
from pathlib import Path

from src.pipeline.views import connect

EVAL = Path("reports/eval_confirm_tfidf_final/eval_results.jsonl")
OUT = Path("reports/roi_analysis.md")
YEAR = 2025                                   # last full year in the data
DISPUTES = ("Cargo no reconocido", "Cobro indebido")
# ASSUMPTIONS (not in the dataset): fully loaded cost of one contact-center agent hour in USD, and the monthly cost
# of running the agent in production (a paid container instead of the free demo tier, plus monitoring).
AGENT_COST_PER_HOUR = (6.0, 10.0, 15.0)
INFRA_USD_PER_MONTH = 50.0


def one(c, sql):
    return c.execute(sql).fetchone()


def main():
    c = connect()
    contacts = one(c, f"select count(*) from call_center_interactions where reason_category='Queja' "
                      f"and year(interaction_date)={YEAR}")[0]
    total_complaints, dispute_complaints = one(c, f"""select count(*), count(*) filter (where subcategory in {DISPUTES})
        from complaints where year(creation_date)={YEAR}""")
    aht_s, wait_s, fcr, followup = one(c, """select median(duration_seconds), avg(wait_time_seconds),
        avg(was_resolved::int), avg(requires_followup::int) from call_center_interactions where reason_category='Queja'""")
    per_agent_month = one(c, "select avg(total_monthly_interactions) from service_agents where agent_status='Active'")[0]
    csat_res, csat_unres = one(c, """select avg(s.main_score) filter (where i.was_resolved),
        avg(s.main_score) filter (where not i.was_resolved) from satisfaction_surveys s
        join call_center_interactions i using (interaction_id) where i.reason_category='Queja' and s.survey_type='CSAT'""")
    first_resp_days, res_days, sla = one(c, f"""select median(date_diff('hour', creation_date, first_response_date))/24.0,
        median(resolution_days), avg(sla_breached::int) from complaints where subcategory in {DISPUTES}""")

    rows = [json.loads(line) for line in EVAL.open()]
    hybrid = [r for r in rows if r["system"] == "hybrid"]
    contained_ok = sum(r["success"] and not r["handed_off"] for r in hybrid) / len(hybrid)
    unsafe = sum(r["unsafe"] for r in hybrid)
    # same definition as the evaluation report: total LLM spend over successful automated resolutions
    resolved = [r for r in hybrid if r["expected_outcome"] == "resolved" and r["success"]]
    llm_per_resolution = sum(r["cost_usd"] for r in hybrid) / max(1, len(resolved))

    share = dispute_complaints / total_complaints
    dispute_contacts = contacts * share
    agent_s_per_year = per_agent_month * 12 * aht_s

    def scenario(containment):
        automated = dispute_contacts * containment
        hours = automated * aht_s / 3600
        return automated, hours, automated * aht_s / agent_s_per_year, automated * wait_s / 3600

    lines = [
        "# ROI of automated dispute intake (generated by `python -m src.eda.roi` — do not edit)", "",
        "**What this is.** An estimate of what the agent saves if it takes the dispute-intake contacts that LATAM Bank's "
        "call center handles today. Contact volumes, handling times and satisfaction come from the dataset; "
        "automation rate, unsafe rate and LLM cost come from the held-out evaluation of the deployed configuration. "
        "The dataset is synthetic and near-uniform in places (see `eda_findings.md` Q12), so read the result as a "
        "method with order-of-magnitude numbers, not a forecast.", "",
        "## Inputs from the data", "",
        "| input | value | source |", "|---|---|---|",
        f"| Complaint contacts in {YEAR} | {contacts:,} | `call_center_interactions`, reason = Queja |",
        f"| Share of complaints that are disputes (unrecognized charge + undue fee) | {share:.1%} | `complaints` {YEAR} |",
        f"| → estimated dispute contacts per year | **{dispute_contacts:,.0f}** | contacts × share (assumes contacts mirror the complaint mix) |",
        f"| Median handling time of a complaint contact | {aht_s:.0f} s | `duration_seconds` |",
        f"| Average customer wait before an agent | {wait_s:.0f} s | `wait_time_seconds` |",
        f"| First-contact resolution / follow-up needed | {fcr:.1%} / {followup:.1%} | `was_resolved`, `requires_followup` |",
        f"| Interactions per agent per month | {per_agent_month:.0f} | `service_agents` (active) |",
        f"| CSAT (1–4) when the complaint contact is resolved vs not | {csat_res:.2f} vs {csat_unres:.2f} | `satisfaction_surveys` × interactions |",
        f"| Dispute complaints: median days to first response / to resolution, SLA breached | {first_resp_days:.1f} d / {res_days:.0f} d, {sla:.1%} | `complaints` |",
        "", "## Inputs from the evaluation (deployed hybrid, 230 sealed conversations)", "",
        "| input | value |", "|---|---|",
        f"| Conversations fully handled with no transfer and a correct outcome | {contained_ok:.1%} |",
        f"| Unsafe outcomes | {unsafe} / {len(hybrid)} |",
        f"| LLM cost per automated resolution | ${llm_per_resolution:.4f} |",
        "", "The evaluation mix over-weights hard cases on purpose (74 of 230 must be escalated), so the real "
        "containment of ordinary dispute traffic is likely higher; the table below varies it.", "",
        "## Savings per year", "",
        "| containment | contacts automated | agent hours saved | agent FTE freed | customer wait saved (h) | "
        + " | ".join(f"net USD saved @ ${r:.0f}/h" for r in AGENT_COST_PER_HOUR) + " |",
        "|---|---|---|---|---|" + "---|" * len(AGENT_COST_PER_HOUR)]
    for cont in (0.40, 0.55, contained_ok):
        automated, hours, fte, wait_h = scenario(cont)
        running = INFRA_USD_PER_MONTH * 12 + automated * llm_per_resolution
        net = [hours * r - running for r in AGENT_COST_PER_HOUR]
        label = f"{cont:.0%}" + (" (eval)" if cont == contained_ok else "")
        lines.append(f"| {label} | {automated:,.0f} | {hours:,.0f} | {fte:.1f} | {wait_h:,.0f} | "
                     + " | ".join(f"{n:,.0f}" for n in net) + " |")
    human_cost = [aht_s / 3600 * r for r in AGENT_COST_PER_HOUR]
    lines += [
        "", "## Cost per resolution", "",
        "| | cost per contact |", "|---|---|",
        f"| Human agent (median {aht_s:.0f} s) | " + " / ".join(f"${h:.2f}" for h in human_cost)
        + " at " + " / ".join(f"${r:.0f}" for r in AGENT_COST_PER_HOUR) + " per hour |",
        f"| Agent: LLM | ${llm_per_resolution:.4f} |",
        f"| Agent: infrastructure (${INFRA_USD_PER_MONTH:.0f}/month over the eval-containment volume) | "
        f"${INFRA_USD_PER_MONTH * 12 / scenario(contained_ok)[0]:.3f} |",
        "", f"**Per contact the agent costs about {(llm_per_resolution + INFRA_USD_PER_MONTH * 12 / scenario(contained_ok)[0]) / human_cost[1]:.0%} "
        f"of a human-handled contact at ${AGENT_COST_PER_HOUR[1]:.0f}/h.** This ratio does not depend on the bank's size; "
        "the absolute savings above do, and this synthetic bank is small (about 39k complaint contacts a year).",
        "", "## What it does not claim", "",
        "- The agent automates **intake**: identity, finding the charge, filing a verified dispute, blocking the card. "
        f"Investigating the dispute still takes the bank's process (median {res_days:.0f} days today); the agent removes "
        f"the {first_resp_days:.1f}-day wait for a first response on the intake step, not the investigation.",
        f"- Satisfaction: resolved complaint contacts score {csat_res:.1f} vs {csat_unres:.1f} for unresolved ones "
        f"(CSAT 1–4). Only {fcr:.0%} are resolved on first contact today; the evaluation suggests the agent resolves "
        "in-scope intake in one conversation, but no CSAT was measured on the agent itself.",
        "- Costs exclude building and maintaining the system, and the human time spent on the cases it escalates "
        "(those already reach an agent today, with everything verified, so handling should be shorter, but that is "
        "not measured).",
        "- Agent cost per hour and infrastructure cost are assumptions, shown as scenarios.",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
