"""Smoke run on the real sandbox: the three required paths plus Portuguese, in both modes, through the HTTP API.
Writes reports/agent_smoke.md. Usage: uv run --group embeddings --env-file .env python scripts/smoke_agent.py
Costs a few tenths of a cent (hybrid mode only). Uses a throwaway copy of the sandbox so no demo state leaks."""
import shutil
import sys
import tempfile
from pathlib import Path

from fastapi.testclient import TestClient

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from src.agent.api import create_app  # noqa: E402
from src.agent.factory import build_agent  # noqa: E402
from src.bank import config, db  # noqa: E402


def pick_customer(conn):
    return conn.execute("""
        select c.document_number, t.merchant_name, t.amount, t.currency
        from customers c join transactions t using (customer_id) join products p on p.product_id = t.product_id
        where c.customer_status = 'Active' and c.mobile_phone is not null and p.product_type like 'Tarjeta%'
          and p.product_status = 'Active' and t.transaction_status = 'Approved' and t.merchant_name is not null
          and coalesce(t.amount_usd, t.amount) < 400 and t.local_date >= '2026-05-01'
          and c.customer_id not in (select customer_id from complaint_flags where is_repeat_complainer = 1)
        order by c.customer_id limit 1""").fetchone()


def run(mode: str, lines: list[str]) -> None:
    tmp = Path(tempfile.mkdtemp()) / "sandbox.db"
    shutil.copy(config.SANDBOX_PATH, tmp)
    conn = db.connect(tmp)
    db.create_schema(conn)
    client = TestClient(create_app(conn=conn, agent=build_agent(conn, mode), demo_mode=True))
    doc, merchant, amount, currency = pick_customer(conn)
    scripts = {
        "normal (es)": [f"No reconozco un cargo de {amount:.0f} en {merchant}", doc, "<otp>", "sí", "no"],
        "ambiguous → unsupported (pt)": ["Quero um empréstimo", "oi"],
        "human-required (es)": ["me robaron la tarjeta y hay 3 compras que no hice", doc, "<otp>", "sí"],
    }
    lines.append(f"\n## Mode: {mode}\n")
    for name, turns in scripts.items():
        cid = client.post("/v1/conversations").json()["conversation_id"]
        lines.append(f"### {name}\n")
        for msg in turns:
            if msg == "<otp>":
                msg = client.get(f"/v1/demo/sms/{cid}").json()["sms"].split()[-1]
                shown = "<OTP from simulated SMS>"
            else:
                shown = "<document number>" if msg == doc else msg
            out = client.post("/v1/chat", json={"conversation_id": cid, "message": msg}).json()
            lines.append(f"- **customer:** {shown}\n  **agent** [{out['stage']}, {out['latency_ms']:.0f} ms, ${out['cost_usd']:.6f}]: "
                         + out["reply"].replace("\n", " / "))
        lines.append("")
    lines.append(f"Metrics: `{client.get('/v1/metrics').json()}`\n")


if __name__ == "__main__":
    report = ["# Agent smoke run (generated by scripts/smoke_agent.py)",
              "Real sandbox copy, real router, real OpenRouter model in hybrid mode. Documents and OTPs are redacted."]
    for mode in ("baseline", "hybrid"):
        run(mode, report)
    Path("reports/agent_smoke.md").write_text("\n".join(report))
    print("\n".join(report))
